POST http://127.0.0.1:7777/perform_query
Accept: text/plain
Content-Type: application/json

{
  "file_name": "apache_logs.txt",
  "cmd1": "filter",
  "value1": "GET",
  "cmd2": "limit",
  "value2": "10"
}

###

POST http://127.0.0.1:7777/perform_query
Accept: text/plain
Content-Type: application/json

{
  "file_name": "apache_logs.txt",
  "cmd1": "map",
  "value1": "0",
  "cmd2": "unique",
  "value2": "100"
}

###

POST http://127.0.0.1:7777/perform_query
Accept: text/plain
Content-Type: application/json

{
  "file_name": "apache_logs.txt",
  "cmd1": "filter",
  "value1": "99.6.61.4",
  "cmd2": "sort",
  "value2": "True"
}

###

POST http://127.0.0.1:7777/perform_query
Accept: text/plain
Content-Type: application/json

{
  "file_name": "apache_logs.txt",
  "cmd1": "map",
  "value1": "0",
  "cmd2": "sort",
  "value2": "True"
}

###

POST http://127.0.0.1:7777/perform_query
Accept: text/plain
Content-Type: application/json

{
  "file_name": "apache_logs.txt",
  "cmd1": "map",
  "value1": "0",
  "cmd2": "limit",
  "value2": "15z"
}

###

POST http://127.0.0.1:7777/perform_query
Accept: text/plain
Content-Type: application/json

{
  "file_name": "apache_logs.txt",
  "cmd1": "map",
  "value1": "0",
  "cmd2": "sort",
  "value2": "True"
}

###

POST http://127.0.0.1:7777/perform_query
Accept: text/plain
Content-Type: application/json

{
  "file_name": "apache_logs.txt",
  "cmd1": "sort",
  "value1": "False",
  "cmd2": "regex",
  "value2": "images\\/\\w+\\.png"
}

###
